name: CI PUSH TO ECR/MANIFEST REPO

on:
  push:
    branches:
      - main
  
jobs:
  Build_and_push_ECR:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build & image 
        env:
          AWS_ECR_IMAGE: ${{ secrets.AWS_ECR_IMAGE }}
        run: |
          docker build -t $AWS_ECR_IMAGE:latest .
          
      - name: Push image to AWS ECR
        env:
          AWS_ECR_IMAGE: ${{ secrets.AWS_ECR_IMAGE }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_REPOSITORY
          docker tag $AWS_ECR_IMAGE:latest $AWS_ECR_REPOSITORY/$AWS_ECR_IMAGE:$TAG
          docker push $AWS_ECR_REPOSITORY/$AWS_ECR_IMAGE:$TAG
        
  manifest_helm:
    runs-on: ubuntu-latest
    needs: ['Build_and_push_ECR']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: paulodisfarce/HELM-ArgoCD
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}
      - name: setup git config
        env:
          GH_EMAIL: ${{ secrets.GH_EMAIL }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          TAG: ${{ github.sha }}
        run: |
          git config --global user.email $GH_EMAIL
          git config --global user.name $GH_USERNAME
          sed -i "s#tag:.*#tag: $TAG#g" helm-chart/application/values.yaml
          git add -A
          git commit -am "Trocando Tag - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main


